openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/users/{id}/:
    get:
      operationId: retrieveUser
      description: Updates and retrieves user accounts
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  username:
                    type: string
                    readOnly: true
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
          description: ''
    put:
      operationId: updateUser
      description: Updates and retrieves user accounts
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                first_name:
                  type: string
                  maxLength: 30
                last_name:
                  type: string
                  maxLength: 150
          application/x-www-form-urlencoded:
            schema: *id001
          multipart/form-data:
            schema: *id001
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  username:
                    type: string
                    readOnly: true
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
          description: ''
    patch:
      operationId: partial_updateUser
      description: Updates and retrieves user accounts
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this user.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id002
              properties:
                first_name:
                  type: string
                  maxLength: 30
                last_name:
                  type: string
                  maxLength: 150
          application/x-www-form-urlencoded:
            schema: *id002
          multipart/form-data:
            schema: *id002
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  username:
                    type: string
                    readOnly: true
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
          description: ''
  /api/v1/users/:
    post:
      operationId: createUser
      description: Creates user accounts
      parameters: []
      requestBody:
        content:
          application/json:
            schema: &id003
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+\Z
                  maxLength: 150
                password:
                  type: string
                  writeOnly: true
                  maxLength: 128
                first_name:
                  type: string
                  maxLength: 30
                last_name:
                  type: string
                  maxLength: 150
                email:
                  type: string
                  format: email
                  maxLength: 254
              required:
              - username
              - password
          application/x-www-form-urlencoded:
            schema: *id003
          multipart/form-data:
            schema: *id003
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    format: uuid
                    readOnly: true
                  username:
                    type: string
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                    pattern: ^[\w.@+-]+\Z
                    maxLength: 150
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
                  email:
                    type: string
                    format: email
                    maxLength: 254
                  auth_token:
                    type: string
                    readOnly: true
                required:
                - username
          description: ''
  /api-token-auth/:
    post:
      operationId: CreateObtainAuthToken
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
