# Generated by Django 3.0.8 on 2020-08-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('established', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tent_only', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('campground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to='campgrounds.Campground')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campgrounds', models.ManyToManyField(to='campgrounds.Campground')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campers', to='campgrounds.Campsite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
